### ISSUE TITLE
Call to undefined function morphos\Russian\nameCase()

### ISSUE THREAD

**Issue by errogaht** [wapmorgan/Morphos-Blade#1]
Call to undefined function morphos\Russian\nameCase()
@name('Алексей', 'винительный')

**Comment by wapmorgan** [comment]
Thanks for feedback. 
Updated adapter to **1.4.1** version. Please update it and check again.

**Comment by wapmorgan** [comment]
What's about the update?

**Comment by wapmorgan** [comment]
Do you experience this problem now?

**Comment by errogaht** [comment]
Hello! Sorry but im not test it.
Probably i want to use your library like this
`@name('Москва', 'винительный') // Москву`
and for other cities.
Your library is work this way?

**Comment by wapmorgan** [comment]
Yes, Morphos can do it. But it has no direct way for it. In PHP you can use morphos API:
```php
var_dump((new morphos\Russian\FirstNamesDeclension())->getCase('Москва', 'винительный', morphos\NamesDeclension::WOMAN));
string(12) "Москву"
```
Note: it's very important to specify proper gender for geographical name.

**Comment by errogaht** [comment]
thankyou.
Any way to detect gender of city?

**Comment by wapmorgan** [comment]
Ok, I've tested few city names and can resume:
1. You can use `MAN` gender for all cities, even if it looks like a female name: "Жуковка", "Москва", "Уфа".
    ```php
    var_dump(array_map(function ($value) { return (new morphos\Russian\FirstNamesDeclension())->getCase($value, 'винительный', 'm');}, array('Москва', 'Уфа', 'Йошкар-ола', 'Ленинград', 'Днепропетровск', 'Краснодар', 'Белгород')));

    /* array(7) {
      [0]=>
      string(12) "Москву"
      [1]=>
      string(6) "Уфу"
      [2]=>
      string(19) "Йошкар-олу"
      [3]=>
      string(20) "Ленинграда"
      [4]=>
      string(30) "Днепропетровска"
      [5]=>
      string(20) "Краснодара"
      [6]=>
      string(18) "Белгорода"
    } */
    ```
2. Some city names will not be deflected properly, like "Елец", "Изобильный" or "Дюртюли" due to lack of rules for this cases. They are treated like immutable so they will be retutned without changes.
    ```
    array(6) {
      ["nominative"]=>
      string(14) "Дюртюли"
      ["genitive"]=>
      string(14) "Дюртюли"
      ["dative"]=>
      string(14) "Дюртюли"
      ["accusative"]=>
      string(14) "Дюртюли"
      ["ablative"]=>
      string(14) "Дюртюли"
      ["prepositional"]=>
      string(17) "о Дюртюли"
    }
   ```
3. Some city names will not be handled properly due to their complexity like "Нижний Новгород" or "Ростов-на-Дону".

But most of names handled properly, so you can use library for this case.

**Comment by errogaht** [comment]
thank you very mutch!
